# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.gitignore'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Create Settings file
        run: |
          echo $MVN_SETTINGS > settings.xml && cat settings.xml
        env:
          MVN_SETTINGS: ${{ secrets.BOT_SETTINGS }}
      - name: Build with Maven
        run: |
          mvn -B -X package -s settings.xml --file pom.xml
        env:
          BOT_NAME: SomeSecBot
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -X -s settings.xml
        env:
          BOT_NAME: SomeSecBot
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}